name: Build and Deploy to Production

on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: '* * 1 1 *'

jobs:
  build-deploy-prod:
    runs-on: ubuntu-latest
    env:
      APP_NAME: name-of-app-prod
      APP_PATH: /__app/name-of-app-prod
      MAIN_HOST_DIR: /home/releases/name-of-app-prod/releases
    steps:
      - uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "prod-"
          append_to_pre_release_tag: ""
          default_bump: patch

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, fileinfo, gd, gettext, intl, mbstring, exif, mysqli, pdo_mysql, pdo_sqlite, zip
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip the project excluding .git, .github, node_modules, deploy-prod.sh, and deploy-prod.sh
        run: zip -r project-${{ steps.tag_version.outputs.new_tag }}.zip . -x deploy-prod.sh -x deploy-prod.sh -x '.git/*' -x '.github/*' -x 'node_modules/*'

      - name: Prepare zip file and deploy-prod.sh for upload
        run: |
          mkdir temp_for_upload
          cp project-${{ steps.tag_version.outputs.new_tag }}.zip temp_for_upload/
          cp deploy-prod.sh temp_for_upload/

      - name: Sync files to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PROD_CPANEL_FTP_HOST }}
          username: ${{ secrets.PROD_CPANEL_FTP_USERNAME }}
          password: ${{ secrets.PROD_CPANEL_FTP_PASSWORD }}
          local-dir: temp_for_upload/
          server-dir: ${{ env.APP_PATH }}/releases/${{ steps.tag_version.outputs.new_tag }}/
