name: Laravel Pint Code Style

on:
  pull_request:
    branches:
      - development

jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl, fileinfo, gd, gettext, intl, mbstring, exif, mysqli, pdo_mysql, pdo_sqlite, zip
          tools: composer:v2
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run Laravel Pint
        run: ./vendor/bin/pint
